/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;


import org.junit.jupiter.api.Test;

import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void hashTable() {

    HashTable<Object, Object> Table = new HashTable<>();
    Table.add("hello", 5);
    Table.add("from", 7);
    Table.add("hash", 8);
    Table.add("table", 2);
    System.out.println(Table);
    assertEquals(6, Table.hash("Test"));

    assertEquals(" [ {from:7} ] ", Table.printOneBucket("Test"));
    assertEquals("HashTable{hashTable=[ [ {table:2} {hash:8} ] , null,  [ {hello:5} ] , null, null, null,  [ {from:7} ] , null, null, null]}", Table.toString());
    assertEquals(5, Table.get("hello"));
    assertNull(Table.get("null"));


  }


  @Test
  void hashMap_repeated_word() {


    String book = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
    assertEquals("the", App.repeatedWord(book));
  }

  @Test

  public void tree() {
    TreeSet<String> tree1= new TreeSet<>();
    tree1.add("alaa");
    tree1.add("A");
    tree1.add("B");
    tree1.add("C");
    TreeSet<String> tree2 = new TreeSet<>();
    tree2.add("alaa");
    tree2.add("X");
    tree2.add("Q");
    tree2.add("M");
    assertEquals("HashTable{hashTable=[null, null, null, null, null, null, null, null, null,  [ {alaa:alaa} ] ]}",  App.treeIntersection(tree1, tree2).toString());
  }

  }

