/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

java.util.stack (Integer) stack = new java.util.stack<> (); 

public class App {
  public static void main(String[] args) {



  }
}
