/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue;

public class App {
//    public String getGreeting() {
//        return "Hello World!";
//    }
//
    public static void main(String[] args) {


      Stack<String> stack = new Stack<>();
      stack.push("hi");
      stack.push("there");
      stack.push("I'm Alaa");



      System.out.println(stack.peek());
      System.out.println(stack.pop());



      System.out.println(stack.top.value);
      System.out.println("--------queue------");

      Queue queue = new Queue();
      queue.enqueue("hi");
      queue.enqueue("there");
      System.out.println(queue.rear.value);
      System.out.println(queue.peek());
      System.out.println(queue.rear.value);

//      System.out.println(queue.rear.toString());



    }


}
