/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MergeSort;

import java.util.Arrays;

public class App {

  public static void main(String[] args) {
    int[] arr ={8,4,23,42,16,15};
    System.out.println(Arrays.toString(MergeSort(arr)));

  }
  public static int[] MergeSort(int[] arr) {

    if (arr.length > 1) {
      int mid = arr.length / 2;
      int[] left = Arrays.copyOfRange(arr, 0, mid);
      int[] right = Arrays.copyOfRange(arr, mid, arr.length);
      MergeSort(left);
      MergeSort(right);
      merge(left, right, arr);
    }
    return arr;
  }


  public static void merge(int[] left, int[] right, int[] arr) {
    int i = 0, j = 0, k = 0;

    while (i < left.length && j < right.length) {
      if (left[i] <= right[j]) {
        arr[k] = left[i];
        i++;
      } else {
        arr[k] = right[j];
        j++;
      }
      k++;
    }

    if (i == left.length) { // left arr is empty
      for (int index = j; index < right.length; index++) {
        arr[k] = right[index];
        k++;
      }
    } else {  // right arr is empty
      for (int index = i; index < left.length; index++) {
        arr[k] = left[index];
        k++;
      }
    }
  }
}

