/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionSort;

import java.lang.reflect.Array;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int [] number = {5,1,8};
        var sorter = new InsertionSort();
        sorter.sort(number);
      System.out.println(Arrays.toString(number));
    }


}
