/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;

public class App <K, T> {


  public static void main(String[] args) {
HashTable<Object, Object> Table = new HashTable<>();
Table.add("hello", 5);
    Table.add("from", 7);
    Table.add("hash", 8);
    Table.add("table", 2);
//    System.out.println(Table);
    System.out.println(Table.get("hello"));
//
//
//    System.out.println(Table.contains("from"));
//
//    System.out.println(Table.hash("hash"));
//    System.out.println(Table.hash("from"));
//    System.out.println(Table.hash("hello"));
//
//
//    System.out.println(Table);

    System.out.println(repeatedWord("Once upon a time, there was a brave princess who..."));
    System.out.println(repeatedWord("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only..."));




  }
  public static String repeatedWord(String sentence) {
    Map<String,String> hashMap = new HashMap<>();
    String[] allWords = sentence.split(" ");
    for (String word : allWords) {
      word = word.toLowerCase();
      if (hashMap.containsKey(word))return word;
      else  hashMap.put(word,word);
    }
    return null;
  }


  }

