/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;


public class App {
    public static void main(String[] args) {
        LinkedList<Integer> linkedList = new LinkedList<Integer>();
        linkedList.insert(1);
        linkedList.insert(2);
        linkedList.insert(3);

        System.out.println(linkedList.toString());
        System.out.println(linkedList.includes(4));
    }
}
