/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;


public class App {
    public static void main(String[] args) {
        LinkedList<Integer> linkedList = new LinkedList<Integer>();
        linkedList.insert(1);
        linkedList.insert(2);
        linkedList.insert(3);

        System.out.println(linkedList.toString());
        System.out.println(linkedList.includes(4));
        System.out.println("kthhhhhhh");
        System.out.println(linkedList.kth(0));

        ////////////////////////////////
        LinkedList<Integer> linkedList2 = new LinkedList<>();

        linkedList2.append(1);
        linkedList2.append(2);
        linkedList2.append(3);
        linkedList2.append(4);
        System.out.println(linkedList2.toString());
        System.out.println();
        linkedList2.insertBefore(2, 8);
        System.out.println(linkedList2);
      linkedList2.insertBefore(8, 9);
      System.out.println(linkedList2);

      //////////////////
        System.out.println();
        linkedList2.insertAfter(1, 7);
        System.out.println(linkedList2);





    }
}
